# Generated by Django 5.2 on 2026-07-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='Parent category group (e.g. Icons and leadership)', max_length=255)),
                ('name', models.CharField(help_text='Specific award title (e.g. Student of the Year)', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active categories appear on the public form')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['group_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NominationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, help_text='Toggle to open/close public award nominations')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nomination Settings',
                'verbose_name_plural': 'Nomination Settings',
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(max_length=255)),
                ('nominee_name_normalized', models.CharField(db_index=True, editable=False, max_length=255)),
                ('nominee_photo', models.ImageField(upload_to='nominations/nominees/')),
                ('nominator_name', models.CharField(max_length=255)),
                ('nominator_phone', models.CharField(max_length=50)),
                ('nominator_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='nominations.category')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('category', 'nominee_name_normalized'), name='unique_category_nominee')],
            },
        ),
    ]
