# Generated by Django 5.2 on 2026-07-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='nominee_email',
            field=models.EmailField(blank=True, help_text='Nominee email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='nominee_phone',
            field=models.CharField(blank=True, help_text='Nominee phone number', max_length=50, null=True),
        ),
    ]
