# Generated by Django 5.2 on 2026-08-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0004_rename_eleesa_to_aces'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='nominee_whatsapp',
            field=models.CharField(blank=True, help_text='Nominee WhatsApp Number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='nominator_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='nominator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='nominator_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='nominee_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='nominee_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='nominee_photo',
            field=models.ImageField(blank=True, null=True, upload_to='nominations/nominees/'),
        ),
    ]
