# Generated by Django 5.0 on 2024-01-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.FileField(default='images/events/default.jpg', upload_to='images/events'),
        ),
    ]
