# Generated by Django 5.2 on 2026-01-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_options_remove_event_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.URLField(blank=True, help_text='Google Maps link for the venue', max_length=500),
        ),
    ]
