# Generated by Django 5.2 on 2026-02-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='webhooklog',
            name='payment_log_referen_f5bbcd_idx',
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['status'], name='payment_log_status_6af17f_idx'),
        ),
    ]
