# Generated by Django 5.2 on 2025-12-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderitem_selected_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_color',
            field=models.CharField(blank=True, help_text='Color of the main image (e.g. Black)', max_length=50, null=True),
        ),
    ]
