# Generated by Django 5.2 on 2025-12-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_completed_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when order was delivered', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when order was prepared/completed', null=True),
        ),
    ]
