# Generated by Django 5.2 on 2025-12-18 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_created_at_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique coupon code (auto-generated or custom)', max_length=50, unique=True)),
                ('owner_name', models.CharField(help_text='Full name of the Committee Head', max_length=100)),
                ('owner_role', models.CharField(help_text='Role in ACES (e.g., President, Secretary, Treasurer)', max_length=100)),
                ('discount_percent', models.PositiveIntegerField(default=10, help_text='Discount percentage (e.g., 10 for 10% off)')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Maximum number of times this coupon can be used')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used')),
                ('expires_at', models.DateTimeField(help_text='Coupon expiration date and time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this coupon is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied to this order', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Applied discount coupon (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.coupon'),
        ),
    ]
