# Generated by Django 5.2 on 2026-01-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_add_coupon_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(default=True, help_text='Show size selector on product page (uncheck for caps, etc.)'),
        ),
    ]
