# Generated by Django 5.2 on 2026-01-19 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_has_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Size label (e.g., S, M, L, XL, 42, 44)', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which sizes appear (lowest first)')),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck if this size is out of stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.product')),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
                'ordering': ['display_order', 'name'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
