# Generated by Django 5.2 on 2026-01-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='e.g. 1 for Small, 2 for Medium', verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='In Stock?'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='name',
            field=models.CharField(help_text="Enter the size here (e.g., 'Small', 'S', '44')", max_length=20, verbose_name='Size Label (e.g., S, M, 42)'),
        ),
    ]
