# Generated by Django 5.2 on 2026-03-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_productsize_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shop_open', models.BooleanField(default=True, help_text='Uncheck to close the ACES Shop to all visitors. Checkout and order creation will be blocked immediately.', verbose_name='Shop is Open')),
                ('closed_message', models.CharField(default='The ACES Shop is currently closed. Please check back soon!', help_text='Custom message shown to visitors when the shop is closed.', max_length=300, verbose_name='Closed Message')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
