# Generated by Django 5.2 on 2026-07-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_add_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='momo_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount customer claims to have paid via MoMo', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='momo_sender_name',
            field=models.CharField(blank=True, help_text="Name on customer's MoMo account (submitted after payment)", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('MOMO', 'Mobile Money'), ('PAYSTACK', 'Paystack')], default='MOMO', help_text='Payment method used for this order', max_length=10),
        ),
    ]
