# Generated by Django 5.2 on 2026-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_momo_amount_paid_order_momo_sender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='momo_receipt',
            field=models.ImageField(blank=True, help_text='Uploaded screenshot of the MoMo transaction receipt', null=True, upload_to='receipts/momo/'),
        ),
    ]
