# Generated by Django 5.0 on 2023-12-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
