# Generated by Django 5.0 on 2024-01-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_alter_scholarship_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='image',
            field=models.FileField(upload_to='images/scholarships'),
        ),
    ]
