# Generated by Django 5.2 on 2026-01-18 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_alter_scholarship_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ['-last_updated']},
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='link',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='application_process',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: submissionLocation, submissionMethod, envelopeRequirements, interviewProcess'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='benefits',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: amount, duration, additionalBenefits'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='contact',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: office, email, applicationForm'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarship',
            name='deadlines',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: submissionDeadline, applicationPeriod'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='eligibility',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: targetStudents, yearLevels, nationality, institution, programType, minimumGrade, etc.'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='provider',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='requirements',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: documents, essays, formatting'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/scholarships'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
