# Generated by Django 5.2 on 2026-01-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_alter_scholarship_options_remove_scholarship_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='application_process',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='deadlines',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='requirements',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='deadline',
            field=models.CharField(blank=True, help_text="Deadline date (e.g., 'Friday, 7th February 2025' or 'Rolling')", max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='link',
            field=models.URLField(blank=True, help_text='Link to scholarship application or more info', max_length=500),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='eligibility',
            field=models.TextField(blank=True, help_text="Eligibility criteria (e.g., '1st year, 2nd year students')"),
        ),
    ]
