# Generated by Django 5.2 on 2026-01-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0006_remove_scholarship_application_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(blank=True, help_text='Select the deadline date', null=True),
        ),
    ]
