# Generated by Django 5.2 on 2025-12-31 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 2024-2025', max_length=50, unique=True)),
                ('hero_banner', models.ImageField(blank=True, help_text='Group photo displayed in the hero section for this year.', null=True, upload_to='executives/banners/')),
                ('description', models.TextField(blank=True, help_text='Optional welcome message from the executives.')),
                ('show_description', models.BooleanField(default=True, help_text='Uncheck to hide the description on the frontend.')),
                ('is_current', models.BooleanField(default=False, help_text='Set this to true to make this the default active year.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('general_secretary', 'General Secretary'), ('financial_secretary', 'Financial Secretary'), ('organizing_secretary', 'Organizing Secretary'), ('pro', 'Public Relations Officer'), ('womens_commissioner', "Women's Commissioner"), ('other', 'Other')], max_length=50)),
                ('position_label', models.CharField(blank=True, help_text="Custom label if position is 'Other', or to override display name.", max_length=100)),
                ('image', models.ImageField(upload_to='executives/profiles/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (e.g., President=1, VP=2)')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='executives.academicyear')),
            ],
            options={
                'verbose_name': 'Executive',
                'verbose_name_plural': 'Executives',
                'ordering': ['order', 'position'],
            },
        ),
    ]
