# Generated by Django 5.2 on 2025-12-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executive',
            options={'ordering': ['academic_year', 'position'], 'verbose_name': 'Executive', 'verbose_name_plural': 'Executives'},
        ),
        migrations.RemoveField(
            model_name='executive',
            name='order',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='position_label',
        ),
        migrations.AlterField(
            model_name='executive',
            name='position',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('general_secretary', 'General Secretary'), ('financial_secretary', 'Financial Secretary'), ('organizing_secretary', 'Organizing Secretary'), ('pro', 'Public Relations Officer'), ('womens_commissioner', "Women's Commissioner")], max_length=50),
        ),
    ]
