# Generated by Django 5.2 on 2025-12-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0002_alter_executive_options_remove_executive_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Optional: Link to Instagram profile', null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Optional: Link to LinkedIn profile', null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Optional: Link to Twitter/X profile', null=True),
        ),
    ]
