# Generated by Django 5.2 on 2025-12-31 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0003_executive_instagram_url_executive_linkedin_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executive',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='twitter_url',
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('email', 'Email'), ('website', 'Website'), ('other', 'Other')], max_length=20)),
                ('url', models.CharField(help_text='URL or Email Address', max_length=255)),
                ('is_visible', models.BooleanField(default=True, help_text='Uncheck to hide this link on the website')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='executives.executive')),
            ],
        ),
    ]
