# Generated by Django 5.2 on 2025-12-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0004_remove_executive_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('email', 'Email'), ('website', 'Website'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('other', 'Other')], max_length=20),
        ),
    ]
