# Generated by Django 5.2 on 2026-01-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0005_alter_sociallink_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='group_photo',
            field=models.ImageField(blank=True, help_text='Group photo displayed on the About page.', null=True, upload_to='executives/group_photos/'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='hero_banner',
            field=models.ImageField(blank=True, help_text='Hero banner for the Executives page.', null=True, upload_to='executives/banners/'),
        ),
    ]
