# Generated by Django 5.2 on 2026-01-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('year', models.IntegerField(help_text='Academic Year (e.g. 1, 2, 3, 4)', primary_key=True, serialize=False)),
                ('year_name', models.CharField(blank=True, help_text="Optional name (e.g. 'Freshman', 'Sophomore')", max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this year from the frontend')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField(help_text='1 for First Semester, 2 for Second Semester')),
                ('semester_name', models.CharField(blank=True, help_text='Optional name', max_length=50, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='courses.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'semester_number'],
                'unique_together': {('academic_year', 'semester_number')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='Course code (e.g. COE 252)', max_length=20, null=True)),
                ('resource_url', models.URLField(help_text='Link to Google Drive or Firebase resource', max_length=500)),
                ('credits', models.IntegerField(blank=True, help_text='Credit hours for this course', null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the course content', null=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order to display in the list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.semester')),
            ],
            options={
                'ordering': ['semester', 'sort_order', 'name'],
            },
        ),
    ]
