# Generated by Django 5.2 on 2026-05-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_businesses', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='snapchat_handle',
            field=models.CharField(blank=True, help_text='e.g., aces_knust', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp_group_link',
            field=models.URLField(blank=True, help_text='Optional WhatsApp Group invite link', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='e.g., aces_knust', max_length=100, null=True),
        ),
    ]
